#!/bin/bash

if [[ "$1" == "init" ]]; then
    export NS_SHELL_PID=$$
    mkdir -p /tmp/ns_${NS_SHELL_PID}
    return 0;
fi

if [[ -z "$NS_SHELL_PID" ]]; then
    export NS_SHELL_PID=$$
    mkdir -p /tmp/ns_${NS_SHELL_PID}
fi

export NS_LAST_CMD

# since init is handled above, the possible options are:
#     run
#     export
#     delete
#     import
ns_subcommand="$1"
shift;

# save_subcommand=
if [[ "$ns_subcommand" == "run-piped" || "$ns_subcommand" == "source-piped" ]]; then
    ns_save_subcommand="$ns_subcommand"
    ns_save_argc=$#
    ns_save_args="$@"
elif [[ "$ns_subcommand" == "run" ]]; then
    ns_save_subcommand="$ns_subcommand"
    ns_save_argc=$#
    ns_save_args="$@"
fi

if [[ "view" == "$ns_subcommand" ]]; then
    ns_view_path=$(NS_PATH="$NS_PATH" ns_which -x "$1")
    if [[ ! -f "$ns_view_path" ]]; then
        echo "Error: '${1}' view file either does not exist or is requires removing the execute permission" 1>&2
        return 1
    fi
    ns_view=$(cat "$ns_view_path")
    ns_view_cat="cat << EOF"$'\n'"${ns_view}"$'\n'"EOF"$'\n'
    eval "$ns_view_cat"
    return $?
fi

if [[ "view-piped" == "$ns_subcommand" ]]; then
    ns_view=$(cat)
    ns_view_cat="cat << EOF"$'\n'"${ns_view}"$'\n'"EOF"$'\n'
    eval "$ns_view_cat"
    return $?
fi

# RUN SUBCMD - REQUIRE+EXPORT+RUN+IMPORT
if [[ "run" == "$ns_subcommand" || "run-piped" == "$ns_subcommand" || "source-piped" == "$ns_subcommand" ]]; then

    ns_script=$(NS_PATH="$NS_PATH" ns_which +x "$1")

    # RUN SUBCMD - (1) REQUIRE
    ns_leading=". ns require "
    ns_require_lines=
    if [[ -n "$ns_script" ]]; then
        ns_require_lines=$(grep "^${ns_leading}" "$ns_script" | sed "s/^${ns_leading}//")
    else
        echo "ns attempted to find an executable script, but 'ns_which ${1}' failed to locate it" 1>&2
        false
    fi
    NS_AUTO_LINES="$ns_require_lines" . ns_auto_export_lines
    # required vars use the same export line (-> import) as other vars

    # RUN SUBCMD - (2) IMPORT LINES -> EXPORT
    ns_leading=". ns import "
    ns_import_lines=
    if [[ -n "$ns_script" ]]; then
        ns_import_lines=$(grep "^${ns_leading}" "$ns_script" | sed "s/^${ns_leading}//")
    else
        echo "ns attempted to find an executable script, but 'ns_which ${1}' failed to locate it" 1>&2
        false
    fi
    # echo "test imp lines ${ns_import_lines}<EOL>" >&2
    NS_AUTO_LINES="$ns_import_lines" . ns_auto_export_lines
    # exps=$(grep "$leading" "$script" | head -1)
    # exps="${exps:$leading_len}"
    # exps_arr=($exps)

    # RUN SUBCMD - (3) RUN
    NS_LAST_CMD="${ns_script}"

    # . ns export "${exps_arr[@]}"
    if [[ "run-piped" == "$ns_save_subcommand" && $ns_save_argc -eq 1 ]]; then
        "$ns_script" </dev/stdin
        # cat | "$script"
    elif [[ "run-piped" == "$ns_save_subcommand" && $ns_save_argc -gt 1 ]]; then
        ns_pipe_chain=$(NS_PATH="$NS_PATH" ARGS="${ns_save_args}" ns_args_to_pipes)
        ns_pipe_chain="cat|${ns_pipe_chain}"
        eval "$ns_pipe_chain"
        # "$script" </dev/stdin
    elif [[ "source-piped" == "$ns_save_subcommand" && $ns_save_argc -eq 1 ]]; then
        . "$ns_script" < /dev/stdin
    elif [[ "run" == "$ns_save_subcommand" && $ns_save_argc -gt 1 ]]; then
        ns_pipe_chain=$(NS_PATH="$NS_PATH" ARGS="${ns_save_args}" ns_args_to_pipes)
        eval "$ns_pipe_chain"
    else
        if [[ ! -x "$ns_script" ]]; then
            echo "ns run attempted for script (${ns_script}) but does not have an execute permission" 1>&2
            false
        else
           "$ns_script" # || (echo "${ns_script} failed ${ns_save_args}" 1>>&2 2>>/dev/null)
        fi
    fi
    ns_ec=$?

    # RUN SUBCMD - (4) EXPORT LINES -> IMPORT
    # Also handles deleting the script's imported variables that aren't exported

    # . ns delete "${exps_arr[@]}"
    # interesting bug..
    #      the code used to try to run delete on all the imports regardless
    #      of whether it was re-exported back. however it was missing the
    #      filename part (so fails trying to do rm w/out '-r' specified)
    #      and stdout was going to dev/null.
    #      Really, what is intended is to just delete the ones that don't get
    #      re-exported.
    ns_leading=". ns export "
    ns_export_lines=
    if [[ -n "$ns_script" ]]; then
        ns_export_lines=$(grep "^${ns_leading}" "$ns_script" | sed "s/^${ns_leading}//")
    else
        echo "ns could not find exports for script (${ns_script})" 1>&2
        false
    fi
    ns_del_lines=$(NS_LHS="$ns_import_lines" NS_RHS="$ns_export_lines" ns_arg_minus)  # (lhs - rhs)
    # delete must happen in reversed line order, otherwise resolving a parameter
    # expression will fail (and instead it tries to delete an empty variable)
    # i.e., should not delete namespace_pattern before myapp_*
    #     # namespace_pattern='myapp_*'
    #     . ns import namespace_pattern
    #     . ns import "${namespace_pattern}"
    ns_del_lines=$(echo "$ns_del_lines" | tac)
    # echo "del_lines=${del_lines}<EOL>">&2
    NS_AUTO_LINES="$ns_del_lines" . ns_auto_delete_lines

    # the script itself already ran an export at the end of the file,
    # now just importing it to make it available to the caller
    NS_AUTO_LINES="$ns_export_lines" . ns_auto_import_lines
    # . ns import "${exps_arr[@]}"

    return $ns_ec
fi

ns_store=/tmp/ns_${NS_SHELL_PID}

ns_saveIFS="$IFS"
IFS=" "$'\n'
while [[ -n "$1" ]]
do
    ns_par="$1"
    # echo "partest: ${par}<END>" >&2
    if [[ "$ns_par" =~ "\$" ]]; then
        ns_par=$(eval "echo \"${ns_par}\"") # dynamic import name,
        #                             # i.e., `. ns import "${bd_ns}"`

        if [[ -z "$ns_par" ]]; then  # get it from storage
            ns_cleaned_par=$(echo "$1" | sed 's/"//g' | sed 's/\$//g' | sed 's/{//g' | sed 's/}//g')
            ns_par="${!ns_cleaned_par}"
        fi
    fi

    ns_name="$ns_par"

    if [[ "delete" == "$ns_subcommand" ]]; then
        if [[ "$ns_name" =~ '*' ]]; then
            NS_PATT="$ns_name" NS_STORE="$ns_store" . ns_delete_pattern
        else
            rm "${ns_store}/${ns_name}" 2>>/dev/null
            export -n "$ns_name"
            unset "$ns_name"
        fi
    elif [[ "export" == "$ns_subcommand" ]]; then
        # val=$(set | grep "${1}=" | head -1 | cut -d '=' -f2)
        # echo "export ${ns_name}" >&2
        if [[ "$ns_name" =~ '*' ]]; then
            # echo "export wildcard ${ns_name}" >&2
            NS_PATT="$ns_name" NS_STORE="$ns_store" . ns_export_pattern
        else
            ns_val="${!ns_name}"
            ns_valenddex=${#ns_val}; ((ns_valenddex--))
            if [[ "${ns_val:$ns_valenddex:1}" == $'\n' ]]; then
                ns_val="${ns_val}{ns_nl}"  # newline gets lost
            fi
            echo "$ns_val" > "${ns_store}/${ns_name}"
        fi
    elif [[ "import" == "$ns_subcommand" ]]; then
        # echo "import ${ns_name}" >&2
        if [[ "$ns_name" =~ '*' ]]; then
            # SAVEGLOBIGNORE="$GLOBIGNORE"
            # GLOBIGNORE="*"
            # set -f  # echo "$-"
            NS_PATT="$ns_name" NS_STORE="$ns_store" . ns_import_pattern
            # set +f
            # GLOBIGNORE="$SAVEGLOBIGNORE"
        else
            ns_val=$(cat "${ns_store}/${ns_name}")
            ns_nldex=${#ns_val}; ((ns_nldex-=7))
            if [[ "${ns_val:$ns_nldex:7}" == "{ns_nl}" ]]; then
                ns_enddex=$ns_nldex; ((ns_enddex--))
                ns_val="${ns_val:0:$ns_enddex}"$'\n'
            fi
            export "${ns_name}=${ns_val}"
            # echo "ns_name=${ns_name}, val=${ns_val}."
        fi
    elif [[ "require" == "$ns_subcommand" ]]; then
        ns_val=$(cat "${ns_store}/${ns_name}")
        ns_nldex=${#ns_val}; ((ns_nldex-=7))
        if [[ "${ns_val:$ns_nldex:7}" == "{ns_nl}" ]]; then
            ns_enddex=$ns_nldex; ((ns_enddex--))
            ns_val="${ns_val:0:$ns_enddex}"$'\n'
        fi
        export "${ns_name}=${ns_val}"
        if [[ -z "$ns_val" ]]; then
            read -p "${ns_name}: " "${ns_name}"
            export "${ns_name}"
        fi
    fi

    shift;

done
IFS="${ns_saveIFS}"
