#!/bin/bash

if [[ "$1" == "init" ]]; then
    export NS_SHELL_PID=$$
    mkdir -p /tmp/ns_${NS_SHELL_PID}
    return 0;
fi

# since init is handled above, the possible options are:
#     run
#     export
#     delete
#     import
subcommand="$1"
shift;

# save_subcommand=
if [[ "$subcommand" == "run-piped" ]]; then
    save_subcommand="$subcommand"
    save_argc=$#
    save_args="$@"
elif [[ "$subcommand" == "run" ]]; then
    save_subcommand="$subcommand"
    save_argc=$#
    save_args="$@"
fi

if [[ "view" == "$subcommand" ]]; then
    view_path=$(NS_PATH="$NS_PATH" ns_which -x "$1")
    if [[ ! -f "$view_path" ]]; then
        echo "Error: '${1}' view file either does not exist or is requires removing the execute permission" 1>&2
        exit 1
    fi
    view=$(cat "$view_path")
    view_cat="cat << EOF"$'\n'"${view}"$'\n'"EOF"$'\n'
    eval "$view_cat"
    return $?
fi

if [[ "view-piped" == "$subcommand" ]]; then
    view=$(cat)
    view_cat="cat << EOF"$'\n'"${view}"$'\n'"EOF"$'\n'
    eval "$view_cat"
    return $?
fi

# for now assume 1 script has 1 ns import
# todo: expand this later to do multiple ns import statements
# also assume the full line is only this format: . ns import a b c
if [[ "run" == "$subcommand" || "run-piped" == "$subcommand" ]]; then
    script=$(NS_PATH="$NS_PATH" ns_which +x "$1")
    leading=". ns import "
    leading_len=${#leading}
    exps=$(grep "$leading" "$script" | head -1)
    exps="${exps:$leading_len}"
    # echo "$exps"
    exps_arr=($exps)

    . ns export "${exps_arr[@]}"
    if [[ "run-piped" == "$save_subcommand" && $save_argc -eq 1 ]]; then
        "$script" </dev/stdin
        # cat | "$script"
    elif [[ "run-piped" == "$save_subcommand" && $save_argc -gt 1 ]]; then
        pipe_chain=$(NS_PATH="$NS_PATH" ARGS="${save_args}" ns_args_to_pipes)
        pipe_chain="cat|${pipe_chain}"
        eval "$pipe_chain"
        # "$script" </dev/stdin
    elif [[ "run" == "$save_subcommand" && $save_argc -gt 1 ]]; then
        pipe_chain=$(NS_PATH="$NS_PATH" ARGS="${save_args}" ns_args_to_pipes)
        eval "$pipe_chain"
    else
        "$script"
    fi
    ec=$?
    . ns delete "${exps_arr[@]}"

    leading=". ns export "
    leading_len=${#leading}
    exps=$(grep "$leading" "$script" | head -1)
    exps="${exps:$leading_len}"
    # echo "$exps"
    exps_arr=($exps)
    # . ns export "${exps_arr[@]}"
    . ns import "${exps_arr[@]}"

    return $ec
fi

ns_store=/tmp/ns_${NS_SHELL_PID}

while [[ -n "$1" ]]
do
    par="$1"
    if [[ "delete" == "$subcommand" ]]; then
        rm "${ns_store}/" 2>>/dev/null
        export -n "$1"
        unset "$1"
    elif [[ "export" == "$subcommand" ]]; then
        # val=$(set | grep "${1}=" | head -1 | cut -d '=' -f2)
        val="${!1}"
        name="${1}"
        echo "$val" > "${ns_store}/${name}"
    elif [[ "import" == "$subcommand" ]]; then
        name="$1"
        val=$(cat "${ns_store}/${name}")
        export "${name}=${val}"
        # echo "name=${name}, val=${val}."
    fi

    shift;

done
