#!/bin/bash

ns_auto_del_lines="$NS_AUTO_LINES"

SAVEIFS="$IFS"
IFS=$'\n'
for ns_del_line in $ns_auto_del_lines
do
    if [[ -z "$ns_del_line" ]]; then
        continue
    fi
    IFS="$SAVEIFS"
    ns_del_arr=($ns_del_line)
    . ns delete "${ns_del_arr[@]}" # must process each line separately and in 
    #                              # order since a dynamic import might have
    #                              # been declared that uses a variable name
    #                              # via parameter expansion that was from a
    #                              # a previous import.
    #                              # e.g.:
    #                              # . ns import 'wiki_*'
    #                              # . ns import "${wiki_dep_namespace_patt}"
    IFS=$'\n'
done
IFS="$SAVEIFS"
