#!/bin/bash

patt="$NS_PATT"
ns_store="$NS_STORE"
patt=$(echo "${patt}" | sed 's/"//g')
for del_name in `set | grep "^${patt}" | cut -d '=' -f1`
do
    rm "${ns_store}/${del_name}" 2>>/dev/null
    export -n "$del_name"
    unset "$del_name"
done
