#!/bin/bash

patt="$NS_PATT"
ns_store="$NS_STORE"
patt=$(echo "${patt}" | sed 's/"//g')

for f in `find ${ns_store} -name "$patt"` # `set | grep "^${patt}" | cut -d '=' -f1`
do
    del_name=$(basename "$f")
    rm "${ns_store}/${del_name}" 2>>/dev/null
done

for del_name in `set | grep "^${patt}" | cut -d '=' -f1`
do
    export -n "$del_name"
    unset "$del_name"
done
