#!/bin/bash

patt="$NS_PATT"
ns_store="$NS_STORE"
patt=$(echo "${patt}" | sed 's/"//g')
for export_name in `set | grep "^${patt}" | cut -d '=' -f1`
do
    val="${!export_name}"
    echo "$val" > "${ns_store}/${export_name}"
    # echo "name:val ${export_name}:${val}" >&2
done
