#!/bin/bash

patt="$NS_PATT"
ns_store="$NS_STORE"
patt1=$(echo "${patt}"| sed 's/"//g')
patt2=$(echo "${patt1}" | sed 's/*/.*/g')
for export_name in `set | grep "^${patt1}" | grep "^${patt2}" | cut -d '=' -f1`
do
    val="${!export_name}"
    valenddex=${#val}; ((valenddex--))
    if [[ "${val:$valenddex:1}" == $'\n' ]]; then
        val="${val}{ns_nl}"  # newline gets lost
    fi
    echo "$val" > "${ns_store}/${export_name}"
    # echo "name:val ${export_name}:${val}" >&2
done
