#!/bin/bash

patt="$NS_PATT"
ns_store="$NS_STORE"
patt=$(echo "${patt}" | sed 's/"//g')
for f in `find ${ns_store} -name "$patt"` # `set | grep "^${patt}" | cut -d '=' -f1`
do
    import_name=$(basename "$f")
    val=$(cat "${ns_store}/${import_name}")
    nsnldex=${#val}; ((nsnldex-=7))
    if [[ "${val:$nsnldex:7}" == "{ns_nl}" ]]; then
        nsenddex=$nsnldex; ((nsenddex--))
        val="${val:0:$nsenddex}"$'\n'
    fi
    export "${import_name}=${val}"
done
