#!/bin/bash

# SPEC TYPE=FTR RECEIVE PIPE

script_path=$(realpath -s "$0")
script_dir="${script_path%/*}"
ns_dir_path=$(realpath "${script_dir}/../../")

PATH="${PATH}:${ns_dir_path}:${script_dir}"; \
    . ns init

exp_test=

# FOO=$(mktemp)
# echo "test" >$FOO & . ns run-piped exp_from_cat <$FOO
# rm -f "$FOO"

. ns run-piped exp_from_cat < <(echo test)  # https://superuser.com/a/705207

if [[ -n "$exp_test" && "$exp_test" == "test" ]]; then
    :
else
    echo "fail => ${script_path}"
    echo "${exp_test} should be 'test'"
fi

