#!/bin/bash

script_path=$(realpath -s "$0")
script_dir="${script_path%/*}"
ns_dir_path=$(realpath "${script_dir}/../../")
index_dir="${ns_dir_path}/doc"
index_file="${index_dir}/README.md"

sorted_index=$(cat)

echo "DOT NS DOC FILES" > "$index_file"

for f in $sorted_index
do
    echo >> "$index_file"
    echo "[${f}](${f})">> "$index_file"
    echo >> "$index_file"
done
