#!/bin/bash

# SPEC TYPE=FTR PIPE TO EXTERNAL PROGRAM

script_path=$(realpath -s "$0")
. "${script_path%/*}/../setup"

exp_a=a

result=`. ns run-piped exp_print < <(echo test) | sed "s/st/sts/" | cat`
# result=`. ns run-piped exp_print < <(echo test) > >(sed "s/st/sts/" | cat)`
# result=$(. ns run-piped exp_print < <(echo test) > >(sed "s/st/sts/" | cat))


if [[ -n "$result" && "$result" == "tests" ]]; then
    :
else
    echo "fail => ${script_path}"
    echo "${result} should be 'tests'"
fi
